#!/usr/bin/env bash
# displayctl
#
# Personal script for setting resolution and wallpaper.

# Include ~/.functions to use xrdb_get_record().
# We use xrdb_get_record() to query xrdb and get the specified record.
source ~/.functions

OUTPUT=`xrdb_get_record Display.monitor`
RESOLUTION=`xrdb_get_record Display.resolution`
BRIGHTNESS=`xrdb_get_record Display.brightness`

WALLPAPER=`xrdb_get_record Display.wallpaper`
LOCKSCREEN=`xrdb_get_record Display.lockscreen`

logo=./res/blank.png
tmpbg=/tmp/bg.png


function print_usage()
{
    echo "Usage: $0 <argument>"
    echo "-d --display      - Set the screen size and brightness."
    echo "-w --wall         - Set the desktop wallpaper."
    echo "-l --lock         - Lock the screen."
    echo "-h --help         - Display this message."
    echo "-u --update       - Update X resources database."
    echo "-c --clear-cache  - Clear previous lockscreen cache."
}

function scale_image()
{
    # $1: The image to scale to your screen resolution.
    width=`echo $RESOLUTION | cut -d "x" -f 1`
    height=`echo $RESOLUTION | cut -d "x" -f 2`

    ffmpeg -i $1 -y -vf scale=$width:$height $tmpbg -loglevel quiet
}

function dim_image()
{
    # $1: The image to apply dim effect to.
    scale_image $1
    convert $tmpbg -fill black -colorize 35% $tmpbg
}

function process_image()
{
    # $1: The image to blur.
    # $2: Should the image be blurred.
    blur_ratio="0:0"
    if [ "$2" == "blur" ]; then blur_ratio="5:5"; fi
    
    scale_image $1
    ffmpeg \
        -i $tmpbg -video_size $RESOLUTION -y -i $logo \
        -filter_complex "boxblur=$blur_ratio,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" \
        -vframes 1 $tmpbg \
        -loglevel quiet
}

function scrot()
{
    # $1: Where the screenshot will be saved to.
    ffmpeg \
        -f x11grab -video_size $RESOLUTION -y -i $DISPLAY \
        -vframes 1 $1 \
        -loglevel quiet
}

function draw_rectangle()
{
    # $1: The image to draw an rectangle on.
    rectangles=" "
    SR=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]*x[0-9][0-9]*[^ ]*')
    for RES in $SR; do
        SRA=(${RES//[x+]/ })
        CX=$((${SRA[2]} + 25))
        CY=$((${SRA[1]} - 30))
        rectangles+="rectangle $CX,$CY $((CX+300)),$((CY-80)) "
    done
    convert $1 -draw "fill black fill-opacity 0.6 $rectangles" $1
}


function clear_cache()
{
    if [ -f $tmpbg ]; then rm $tmpbg; fi
}

function set_display()
{
    # Set the size of the outputs for current screen.
    xrandr 1>/dev/null && xrandr --output $OUTPUT --mode $RESOLUTION
    # Adjust backlight brightness.
    xbacklight -set $BRIGHTNESS
}

function set_wallpaper()
{
    # Copy wallpaper to a temporary location.
    # We might blur it later depending on user's decision.
    if [ "$1" != "$tmpbg" ]; then cp $1 $tmpbg; fi
    if [ "$2" == "blur" ]; then process_image $tmpbg blur; fi
    feh --bg-scale $tmpbg --no-fehbg
}

function lock()
{
    # $1: Lockscreen image path
    letterEnteredColor=ba5e5fff
    letterRemovedColor=ba5e5fff
    passwordCorrect=00000000
    passwordIncorrect=ba5e5fff
    background=00000000
    foreground=ffffffff
    i3lock \
	-n -i "$1" \
	--timepos="x-90:h-ch+30" \
	--datepos="tx+24:ty+25" \
	--clock --datestr "Type password to unlock..." \
	--insidecolor=$background --ringcolor=$foreground --line-uses-inside \
	--keyhlcolor=$letterEnteredColor --bshlcolor=$letterRemovedColor --separatorcolor=$background \
	--insidevercolor=$passwordCorrect --insidewrongcolor=$passwordIncorrect \
	--ringvercolor=$foreground --ringwrongcolor=$foreground --indpos="x+280:h-70" \
	--radius=15 --ring-width=8 --veriftext="" --wrongtext="" \
	--textcolor="$foreground" --timecolor="$foreground" --datecolor="$foreground"
}


case "$1" in
    "")
        # Backup previous image cache, and restore it later.
        set_display
        set_wallpaper $WALLPAPER
        rm $tmpbg
        ;;
        
    -d | --display)
        set_display
        ;;
        
    -w | --wall)
        # Backup previous image cache, and restore it later.
        if [ -f $tmpbg ]; then cp $tmpbg $tmpbg.old; fi
        
        case "$2" in
            "")
                set_wallpaper $WALLPAPER
                ;;
                
            -b | --blur)
                case "$3" in
                    "")
                        set_wallpaper $WALLPAPER blur
                        ;;
                    -d | --dim)
                        dim_image $WALLPAPER
                        set_wallpaper $tmpbg blur
                        ;;
                esac
                ;;
                
            -d | --dim)
                case "$3" in
                    "")
                        dim_image $WALLPAPER
                        set_wallpaper $tmpbg
                        ;;
                    -b | --blur)
                        dim_image $WALLPAPER
                        set_wallpaper $tmpbg blur
                        ;;
                esac
                ;;
        esac
        
        # Restore previous image cache.
        if [ -f $tmpbg.old ]; then rm $tmpbg; mv $tmpbg.old $tmpbg; fi
        ;;
        
    -l | --lock)
        if [ -f $tmpbg ] && [ "$2" != "-s" ] && [ "$2" != "--scrot" ]; then
            echo "Using previous lockscreen cache."
            echo "Run displayctl --clear-cache before applying new effects to your lockscreen."
        else
            echo -n "Generating lockscreen cache, please wait... "
            case "$2" in
                "")
                    process_image $LOCKSCREEN
                    ;;
                    
                -b | --blur)
                    case "$3" in
                        "")
                            process_image $LOCKSCREEN blur
                            ;;
                        -d | --dim)
                            process_image $LOCKSCREEN blur
                            dim_image $tmpbg
                            ;;
                    esac
                    ;;
                    
                -d | --dim)
                    case "$3" in
                        "")
                            dim_image $LOCKSCREEN
                            ;;
                        -b | --blur)
                            dim_image $LOCKSCREEN
                            process_image $tmpbg blur
                            ;;
                    esac
                    ;;
                    
                -s | --scrot)
                    scrot $tmpbg
                    process_image $tmpbg blur
                    ;;
            esac
            echo "[Complete]"
            draw_rectangle $tmpbg
        fi
        lock $tmpbg
        ;;
        
    -u | --update)
        xrdb -merge ~/.Xresources 2>/dev/null
        echo "X resources database has been updated."
        ;;
        
    -c | --clear-cache)
        clear_cache
        echo "The lockscreen cache has been cleared."
        ;;
        
    -h | --help)
        print_usage
        ;;
esac
